config/routes.rb
SampleApp::Application.routes.draw do

namespace :api, :defaults => {:format => :json} do
  match '/rutas_zona', to: 'cliente#rutas_zona'
  match '/rutas_viajes', to: 'cliente#rutas_viajes'
  match '/rutas_busqueda', to: 'cliente#rutas_busqueda'
  match '/ruta_disponibilidad_viaje', to: 'cliente#ruta_disponibilidad_viaje'
  match '/cliente_perfil', to: 'cliente#cliente_perfil'
  match '/cliente_medallas', to: 'cliente#cliente_medallas'
  match '/cliente_checkin', to: 'cliente#cliente_checkin'
  match '/cliente_co2ahorrado', to: 'cliente#cliente_co2ahorrado'
  match '/cliente_co2_viaje', to: 'cliente#cliente_co2_viaje'
  match '/cliente_leaderboard', to: 'cliente#cliente_leaderboard'
  match '/cliente_muestra_retro', to: 'cliente#cliente_muestra_retro'
  match '/cliente_envia_retro', to: 'cliente#cliente_envia_retro'
  match '/cliente_envia_reporte', to: 'cliente#cliente_envia_reporte'
  match '/cliente_envia_sugerencia', to: 'cliente#cliente_envia_sugerencia'
  match '/cliente_reserva_viajes', to: 'cliente#cliente_reserva_viajes'
  match '/viaje_reservaciones', to: 'cliente#viaje_reservaciones'
  match '/viaje_cierre', to: 'cliente#viaje_cierre'
  match '/viaje_apertura', to: 'cliente#viaje_apertura'

  devise_scope :user do
    match '/signup' => 'registrations#create', :via => :post
    match '/signin' => 'sessions#create', :via => :post
    match '/signinfacebook' => 'sessions#createface', :via => :post
    match '/signout' => 'sessions#destroy', :via => :delete
  end
  
end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :conductors

  resources :descuentos

  resources :reportes
  resources :users

  resources :retroaspectos

  resources :retroalimentacions

  resources :reservacions

  resources :niveles
  resources :tipomedallas
  resources :medallas
  
  resources :clientes do
    member do
      get :profile, :muro
    end
  end

  resources :administradors

  resources :rutas
  resources :paradas

  resources :vans

  resources :viajes do
    member do
      get :detalle
    end
  end

  resources :reservacions do
    member do
      get :retroalimentacion
    end
  end

  resources :retroalimentacion, only: [:create, :destroy]

  resources :reservacions, only: [:checkin]

  match '/listareportes', to: 'administradors#listareportes'
  match '/retroalimentaciones', to: 'administradors#reporteretros'
  
  match '/inicio', to: 'administradors#inicio'
  match '/entrega', to: 'administradors#entrega_regalos'
  match '/dashboard', to: 'clientes#dashboard'
  match '/promociones', to: 'clientes#promociones'
  match '/buscar', to: 'clientes#buscarviaje'
  match '/reservaciones', to: 'clientes#reservaciones'
  match '/mis_viajes', to: 'clientes#viajes'
  match '/reporte', to: 'clientes#reporte'
  match '/retro', to: 'reservacions#create_retro'
  match '/retro', to: 'reservacions#retro'
  match '/checkin', to: 'reservacions#checkin'
  match '/compartir_facebook', to: 'clientes#compartir_facebook'

  match '/formapago', to: 'clientes#formapago'
  match '/compracredito', to: 'clientes#compracredito'
  match '/create_transaction_charge', to: 'clientes#create_transaction_charge'

  match '/recarga', to: 'pagos#recarga'
  match '/compra', to: 'pagos#compra'
  match '/entrega_regalos', to: 'administradors#admin_entrega_regalo'

  match '/signup', to: 'users#new'
  match '/signout', to: 'sessions#destroy'

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match '/listadministradores', to: 'administradors#listadministradores'
  match '/administradors', to: 'administradors#index'

  match '/administrar_administradores', to: 'administradors#administradores', via:[:get, :post, :put]
  match '/administrar_administrador_detalle', to: 'administradors#administrador_detalleadministrador', via:[:get, :post, :put]
  match '/administrador_controller/jtable_list',   to: 'administradors#jtable_list',   via: [:get, :post]
  match '/administrador_controller/jtable_filterlist',   to: 'administradors#jtable_filterlist',   via: [:get, :post]
  match '/administrador_controller/jtable_create',   to: 'administradors#jtable_create',   via: [:get, :post]
  match '/administrador_controller/jtable_delete',   to: 'administradors#jtable_delete',   via: [:post]
  match '/administrador_controller/jtable_update',   to: 'administradors#jtable_update',   via: [:post]

  match '/administrador_controller/update',   to: 'administradors#update',   via: [:post,:put]
  match '/administrador_controller/create',   to: 'administradors#create',   via: [:post,:put]

  match '/administrar_conductores', to: 'administradors#conductores', via:[:get, :post, :put]
  match '/conductor_controller/jtable_list',   to: 'conductors#jtable_list',   via: [:post, :get]
  match '/conductor_controller/jtable_filterlist',   to: 'conductors#jtable_filterlist',   via: [:get, :post]
  match '/conductor_controller/jtable_create',   to: 'conductors#jtable_create',   via: [:get, :post]
  match '/conductor_controller/jtable_delete',   to: 'conductors#jtable_delete',   via: [:post]
  match '/conductor_controller/jtable_update',   to: 'conductors#jtable_update',   via: [:post]
  match '/conductor_controller/update',   to: 'conductors#update',   via: [:post,:put]
  match '/conductor_controller/create',   to: 'conductors#create',   via: [:post,:put]

  match '/administrar_promocion_saldo', to: 'administradors#promocion_saldo'
  match '/administrar_saldopromocion', to: 'administradors#saldopromocion', via:[:get, :post, :put]
  match '/administrar_saldopromocion_detalle', to: 'administradors#administrador_detallesaldopromocion', via:[:get, :post, :put]
  match '/saldopromocion_controller/jtable_filterlist',   to: 'saldopromocions#jtable_filterlist',   via: [:get, :post]
  match '/saldopromocion_controller/jtable_delete',   to: 'saldopromocions#jtable_delete',   via: [:post]
  match '/saldopromocion_controller/update',   to: 'saldopromocions#update',   via: [:post,:put]
  match '/saldopromocion_controller/create',   to: 'saldopromocions#create',   via: [:post,:put]

  match '/administrar_promocion_regalo', to: 'administradors#promocion_regalo'
  match '/administrar_regalopromocion', to: 'administradors#saldopromocion', via:[:get, :post, :put]
  match '/administrar_regalopromocion_detalle', to: 'administradors#administrador_detalleregalopromocion', via:[:get, :post, :put]
  match '/regalos_controller/jtable_filterlist',   to: 'regalos#jtable_filterlist',   via: [:get, :post]
  match '/regalos_controller/jtable_delete',   to: 'regalos#jtable_delete',   via: [:post]
  match '/regalos_controller/update',   to: 'regalos#update',   via: [:post,:put]
  match '/regalos_controller/create',   to: 'regalos#create',   via: [:post,:put]

  match '/van_controller/jtable_list',   to: 'vans#jtable_list',   via: [:get, :post]
  match '/van_controller/jtable_filterlist',   to: 'vans#jtable_filterlist',   via: [:get, :post]
  match '/van_controller/jtable_delete',   to: 'vans#jtable_delete',   via: [:post]
  match '/van_controller/create',   to: 'vans#create',   via: [:post,:put]
  match '/van_controller/update',   to: 'vans#update',   via: [:post,:put]
  match '/administrar_van_detalle',   to: 'administradors#administrador_detallevan',   via: [:get, :post, :put]

  match '/ruta_controller/jtable_list',   to: 'rutas#jtable_list',   via: [:get, :post, :put]
  match '/ruta_controller/jtable_filterlist',   to: 'rutas#jtable_filterlist',   via: [:get, :post]
  match '/ruta_controller/jtable_delete',   to: 'rutas#jtable_delete',   via: [:post]
  match '/rutas/:id', to: 'rutas#show', via: [ :get]
  match '/rutas/:id', to: 'rutas#actualizar', via: [:post, :put]

  match '/administrar_ruta_detalle',   to: 'rutas#administrador_detalleruta',   via: [:get, :post, :put]
  match '/administrar_clientes', to: 'administradors#clientes', via:[:get, :post, :put]
  match '/administrar_cliente_detalle', to: 'administradors#administrador_detallecliente', via:[:get, :post, :put]
  match '/cliente_controller/jtable_list',   to: 'clientes#jtable_list',   via: [:post, :get]
  match '/cliente_controller/jtable_filterlist',   to: 'clientes#jtable_filterlist',   via: [:get, :post]
  match '/cliente_controller/jtable_delete',   to: 'clientes#jtable_delete',   via: [:post]
  match '/cliente_controller/jtable_update',   to: 'clientes#jtable_update',   via: [:post]
  match '/cliente_controller/update',   to: 'clientes#update',   via: [:post,:put]
  match '/cliente_controller/create',   to: 'clientes#create',   via: [:post,:put]

  match '/sugerencias', to: 'administradors#sugerencias', via:[:get, :post, :put]
  match '/sugerencia_controller/jtable_list',   to: 'sugerencias#jtable_list',   via: [:post, :get]
  match '/sugerencia_controller/jtable_filterlist',   to: 'sugerencias#jtable_filterlist',   via: [:get, :post]
  match '/administrar_sugerencia_detalle',   to: 'administradors#administrador_detallesugerencia',   via: [:get, :post, :put]

  match '/procesar_busqueda',   to: 'clientes#procesarbusquedaviaje',   via: [:get, :post]
  match '/procesar_busqueda_sinlogin',   to: 'static_pages#procesarbusqueda_sinlogin',   via: [:get, :post]

  match '/administrar_medallas', to: 'administradors#medallas', via:[:get, :post, :put]
  match '/medalla_controller/jtable_list',   to: 'medallas#jtable_list',   via: [:post, :get]
  match '/medalla_controller/jtable_filterlist',   to: 'medallas#jtable_filterlist',   via: [:get, :post]
  match '/medalla_controller/jtable_create',   to: 'medallas#jtable_create',   via: [:get, :post]
  match '/medalla_controller/jtable_delete',   to: 'medallas#jtable_delete',   via: [:post]
  match '/medalla_controller/jtable_update',   to: 'medallas#jtable_update',   via: [:post]
  match '/medalla_controller/update',   to: 'medallas#update',   via: [:post,:put]
  match '/medalla_controller/create',   to: 'medallas#create',   via: [:post,:put]

app/views/shared/_administrador_detalleconductor.html.erb
<ul class="nav nav-tabs pull-right">
  <!--<li><a href="#tab_2-2" data-toggle="tab">Rutas de Conductor</a></li>-->
  <li class="active"><a href="#tab_1-1" data-toggle="tab">Datos de Conductor</a></li>
  <!--<li class="pull-left header"><i class="fa fa-th"></i></li>-->
</ul>
<div class="tab-content">
  <div class="tab-pane active" id="tab_1-1">
    <div id="forma_detalle_conductor">
      <%=
          render 'administradors/form_conductor', locals: { conductor: @conductor, action: @action } #, :disabled => false, :exito => false
         # if :action == 'create'
         #   # @conductor = Conductor.new
         #   # @conductor.user = User.new
         #   render 'administradors/form_conductor', locals: { conductor: @conductor, action: 'create' } , :disabled => false, :exito => false
         # else
         #   if @conductor.present?
         #     render 'administradors/form_conductor', locals: { conductor: @conductor, action: 'update' } , :disabled => false, :exito => false
         #   end
         # end
      %>
    </div>
  </div><!-- /.tab-pane -->
  <div class="tab-pane" id="tab_2-2">
    Sin partial
    </br>
  </div><!-- /.tab-pane -->


</div><!-- /.tab-content -->

app/views/shared/_administrador_stats_box.html.erb
      <div class="row">
            <div id="divconfCorreos" class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-aqua">
                <div class="inner">
                  <h3>
                    <%=number_to_currency(obtener_cuenta_vanpool["balance"], :precision => 2)%>
                  </h3>
                </div>
                <div class="icon">
                  <i class="fa fa-money"></i>
                </div>
                <h4 class="small-box-footer">
                  Saldo en cuenta de Vanpool
                </h4>
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-green">
                <div class="inner">
                  <h3>
                    <%=number_to_currency(obtener_tranferencias_promocion, :precision => 2)%>
                  </h3>
                </div>
                <div class="icon">
                  <i class="fa  fa-gift"></i>
                </div>
                <h4 class="small-box-footer">
                  Depositos en promociones
                </h4>
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-yellow">
                <div class="inner">
                  <h3>
                   <%=numero_clientes%>
                  </h3>
                </div>
                <div class="icon">
                  <i class="fa fa-users"></i>
                </div>
                 <h4 class="small-box-footer">
                  Usuarios registrados
                </h4>
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-red">
                <div class="inner">
                  <h3>
                     <%=number_with_precision(calcula_co2_total, :precision => 2)%>
                  </h3>
                </div>
                <div class="icon">
                  <i class="fa fa-cloud"></i>
                </div>
                <h4 class="small-box-footer">
                  Kilogramos de CO2 ahorrado
                </h4>
              </div>
            </div><!-- ./col -->
      </div>

app/views/shared/_administrador_stats_leaderboard.html.erb
<table class="table table-bordered">
  <tr class="success">
    <th><b>Cliente</b></th>
    <th><b>Puntos</b></th>
  </tr>

<% clientes_top5.each do |cliente| %>
  <tr>
    <td><a><%=cliente.user.name%></a></td>
    <td><%=cliente.puntaje%></td>
  </tr>
<% end %>
</table>

app/views/shared/_header_no_signin.html.erb
<header class="header">
    <a href="<%=root_path%>" class="logo"><img src="/assets/logo.png" class="img" alt="logo Image" /></a>
    <nav class="navbar navbar-static-top" role="navigation">
        <div class="navbar-right">
            <ul class="nav navbar-nav">
                <li class="dropdown ciudad-menu user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span><b>Monterrey MX</b></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <span><b>México</b></span>
                        <li class="ciudad"><a href="#"><span>Ciudad de México</span></li></a>
                        <li class="ciudad"><a href="#"><span>Monterrey</span></li></a>
                        </hr>
                        <span><b>Chile</b></span>
                        <li class="ciudad"><a href="#"><span>Santiago</span></li></a>
                    </ul>
                </li>
                <li class="dropdown registro user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span>Registrate</span></a>
                    <ul class="dropdown-menu">

                            <div class="box-login">
                                <div class="box-body">
                                    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                                    <%= devise_error_messages! %>

                                    <div class="form-group">
                                        <label>Nombre</label>
                                        <%= f.text_field :name, autofocus: true %>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Correo Electrónico</label>
                                        <%= f.email_field :email, autofocus: true %>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Contraseña</label>
                                        <% if @validatable %>
                                            <em>(<%= @minimum_password_length %> characters minimum)</em>
                                        <% end %><br />
                                        <%= f.password_field :password, autocomplete: "off" %>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Verificar Contraseña</label>
                                        <%= f.password_field :password_confirmation, autocomplete: "off" %>
                                    </div>
                                    <div class="box-footer">
                                        <%= f.submit "Crear mi cuenta", class: "btn btn-flat btn-registro pull-right" %>
                                        </br>
                                        <hr></hr>
                                    </div>
                                    <% end %>
                                </div><!-- /.box-body -->
                                <a class="btn btn-block btn-social btn-facebook" href="users/auth/facebook"><i class="fa fa-facebook"></i> Registrate con Facebook </a>   
                            </div>
                        
                    </ul>
                </li>
                <li class="dropdown ingresar user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span>Ingresar</span></a>
                        <ul class="dropdown-menu">
               
                                <div class="box-login">
                                    <div class="box-body">
                                        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Correo Electrónico</label>
                                            <%= f.email_field :email, autofocus: true %>
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Contraseña</label>
                                           <%= f.password_field :password, autocomplete: "off" %>
                                        </div>
                                       
                                        <div class="box-footer">
                                             <%= f.submit "Entrar", class: "btn btn-flat btn-ingresar pull-right" %>
                                        </br>
                                        <hr></hr>
                                        </div>
                                    <% end %>
                                    </div><!-- /.box-body -->
                                    <a class="btn btn-block btn-social btn-facebook" href="users/auth/facebook">
                                        <i class="fa fa-facebook"></i> Iniciar sesión con Facebook
                                    </a>    
                                </div>
                             
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

app/views/shared/_header_signin_admin.html.erb
        <header class="header">
            <a href="<%=root_path%>" class="logo">
                <img src="/assets/logo.png" class="img" alt="logo Image" />
            </a>
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-right">
                    <ul class="nav navbar-nav">                        
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="glyphicon glyphicon-user"></i>
                                <span><%= "#{current_user.name} #{current_user.apellidoPaterno}" %><i class="caret"></i></span>
                            </a>
                             <ul class="dropdown-menu">
                                <!-- Menu Body -->
                                <li class="user-footer">
                                    <div class="pull-left">
        <a href="/inicio" class="btn btn-default btn-flat"><i class="fa fa-eye"></i>Inicio</a>
        </div>
        <div class="pull-right">
        <%= button_to('Cerrar Sesión', destroy_user_session_path, :method => :delete, class:"btn btn-default btn-flat") %>  
        <li> </li>
        </div>
                                              
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

app/views/shared/_modal_conductors.html.erb
<div class="modal fade" id="conductorsModal" tabindex="-1" role="dialog" aria-labelledby="conductorsModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Conductores</h4>
      </div>
      <div class="modal-body">
        <%= render 'shared/show_conductors_table' %>
      </div>
      <div class="modal-footer">
        </br><button type="button" class="btn btn-flat btn-success pull-right" data-dismiss="modal">Seleccionar Conductor</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_show_conductors_table.html.erb
<div id="conductorsTableContainer" class="col-lg-12 col-xs-12">
</div>

<script type="text/javascript" charset="utf-8">
        $(document).ready(function () {
            $('#conductorsTableContainer').jtable({
                messages: {
                    serverCommunicationError: 'Ocurri&oacute; un error al comunicarse con el servidor.',
                    loadingMessage: 'Cargando Registros...',
                    noDataAvailable: '&iexcl;No hay Datos!',
                    addNewRecord: 'Agregar condcutor',
                    editRecord: 'Editar conductor',
                    areYouSure: '¿Está seguro?',
                    deleteConfirmation: '&iquest;Est&aacute; seguro de eliminar este conductor?',
                    save: 'Guardar',
                    saving: 'Guardando',
                    cancel: 'Cancelar',
                    deleteText: 'Eliminar',
                    deleting: 'Eliminando',
                    error: 'Error',
                    close: 'Cerrar',
                    cannotLoadOptionsFor: 'No se pueden cargar las opciones para el campo {0}',
                    pagingInfo: '{0} a {1} de {2}',
                    pageSizeChangeLabel: 'N&uacute;mero de registros',
                    gotoPageLabel: 'Ir a la p&aacute;gina',
                    canNotDeletedRecords: '&excl;No se pudieron eliminar {0} de {1} registros!',
                    deleteProgress: 'Eliminadas {0} de {1} administradores, procesando...'
                },
                title: 'Tabla de Conductores',
                useBootstrap: true,
                paging: true, //Habilitamos paginación.
                pageSize: 10, //Definimos el número de registros a mostrar a 10.
                sorting: true, //Habilitamos ordenación.
                defaultSorting: 'conductors.licenciaConductor ASC', //Definimos la columna default de ordenación.
                defaultDateFormat: 'yy-mm-dd',
                gotoPageArea: 'combobox',
                selecting: true, //Habilitar Seleccion.
                selectingCheckboxes: true, //Mostrar checkbox en la primer columna
                selectOnRowClick: true, //Habilitamos selección con la fila
                deleteConfirm: true,
                actions: {
                    //Aquí va el URL del método del controlador, debemos definirlos primero en config/routes.
                    listAction: '/conductor_controller/jtable_filterlist'
                },
                fields: {
                    //Columna en la tabla. Deben ponerse todas las columnas, si no deben ser visible, solamente
                    //habilitamos la opción list:false. Si un campo no debe editarse configuramos edit:false.
                    id: {
                        key: true,
                        list: false
                    },
                    name: {
                        title: 'Nombre',
                        width: '10%'
                    },
                    licenciaConductor: {
                        title: 'Licencia',
                        width: '10%'
                    },
                    email: {
                        title: 'email',
                        width: '20%'
                    },
                    idTipoUsuario: {
                        list: false,
                        edit: false,
                        create: false
                    },
                    facebookidUsuario: {
                        title: 'Facebook',
                        list: false,
                        edit: false,
                        create: false
                    },
                    openpayidUsuario: {
                        title: 'Openpay',
                        list: false,
                        edit: false,
                        create: false
                    },
                    fechaNacimiento: {
                        title: 'Nacimiento',
                        width: '10%',
                        list: false
                    },
                    estatusConductor: {
                        title: 'Estado',
                        width: '10%',
                        type: 'checkbox',
                        values: {'false':'Inactivo', 'true':'Activo'},
                        list: false,
                        edit: false
                    },
                    created_at: {
                        list: false,
                        edit: false,
                        create: false
                    },
                    updated_at: {
                        list: false,
                        edit: false,
                        create: false
                    }
                },
                //Se crea el evento de selectionchanged
                selectionChanged: function(){
                  	var $selectedRows = $("#conductorsTableContainer").jtable('selectedRows');
                  	if ($selectedRows.length > 0) {
                  		$selectedRows.each(function(){
                  			var record = $(this).data('record');
                  			$("#conductorId").val(record.id);
                  			$("#conductorNombre").val(record.name);
                  			$("#conductorLicencia").val(record.licenciaConductor);
                  		});
                  		
                  	}
                  	
                  }
            });

            // Esta línea carga los datos de la jTable al desplegar la página.
            $('#conductorsTableContainer').jtable('load');
        });
    </script>

app/views/shared/_show_sugerencias.html.erb
<% if(@results.first!=nil)%><%= will_paginate @results, :class => "pagination" %><% @results.each do |result| %><% sug_id = result[:id] %><% result_cercanas = result[:sugerencias_cercanas]%><div class="item-ruta border"><div class="row-fluid"><button class="btn btn-danger btn-sm pull-right" onclick="borrarSugerencia(<%=sug_id%>, <%=result_cercanas%>)"><i class="fa fa-trash-o"></i> Borrar</button></br> <small class="label label-warning"><%= result[:numero_incidencias] %> coincidencias</small></br><small>ORIGEN:</small><b><%= result[:sugerencia].sugerenciaparadas.order('posicion ASC').first.nombre.split(",")[0] %></b></br><small>DESTINO:</small><b><%= result[:sugerencia].sugerenciaparadas.order('posicion ASC').last.nombre.split(",")[0] %></b></br> </br> <%= link_to "Ver Detalle", '#', onclick: "mostrarDetalle(#{sug_id}, #{result_cercanas})", class: "btn btn-buscar-nav btn-flat span5 pull-right" %></div></div><!-- /.item --><% end %><%= will_paginate @results %><!--lista sugs --> <% else %> <div class="item-ruta border"> <h2>No hay sugerencias enviadas.</h2></div><% end %>

app/views/shared/_user_lider.html.erb
<div class="row-fluid">
<div class="span12">
	<% if @validalider==false then %>
		<div class="msg-vacio">
            <h4><b>Aún no eres líder de ruta</b></h4>
        </div>
    <% end %>
</div>
</div>
<div class="row-fluid">
    <% @lider.each do |lid| %>
    <div style="margin:7px" class="span2">
        
                <img src="/assets/medals/major-05.png" class="img-circle" /></br>
                <center><b><%= lid.ruta.nombre%></b></center>
                <center><b><%= lid.record%> check-ins</b></center>
                <center><%= lid.created_at.to_date%></center>
        
    </div><!-- /.item -->
    <% end %>
</div>

app/views/shared/_user_sidebar.html.erb
<section class="sidebar">
    <ul class="sidebar-menu">
        <li class="<%= 'active' if params[:action] == 'dashboard' %>">
            <a href="/dashboard"><i class="fa fa-home"></i> <span>Inicio</span></a>
        </li>
        <li class="<%= 'active' if params[:action] == 'viajes' %>">
            <a href="/mis_viajes"><i class="fa fa-road"></i> <span>Mis viajes</span></a>
        </li>
        <li class="<%= 'active' if params[:action] == 'listar_rutas' %>">
            <a href="/buscar_zona"><i class="fa fa-map-marker"></i> <span>Lista de Rutas</span></a>
        </li>
        <li class="<%= 'active' if params[:action] == 'edit' %>">
            <a href="/users/<%= @current_user.id %>/edit"><i class="fa fa-wrench"></i> <span>Configuración</span></a>
        </li>
         <li class="<%= 'active' if params[:action] == 'reporte' %>">
            <a href="/reporte"><i class="fa fa-check-square-o"></i> <span>Reportar servicio</span></a>
        </li>
    </ul>
</section>

app/views/shared/_user_sugerencia_enviada.html.erb
<i class="fa fa-info"></i>
    <button type="button" class="close" onclick="cerrar()">×</button>
    Sugerencia enviada.