config/routes.rb
SampleApp::Application.routes.draw do

namespace :api, :defaults => {:format => :json} do
  match '/rutas_zona', to: 'cliente#rutas_zona'
  match '/rutas_viajes', to: 'cliente#rutas_viajes'
  match '/rutas_busqueda', to: 'cliente#rutas_busqueda'
  match '/ruta_disponibilidad_viaje', to: 'cliente#ruta_disponibilidad_viaje'
  match '/cliente_perfil', to: 'cliente#cliente_perfil'
  match '/cliente_medallas', to: 'cliente#cliente_medallas'
  match '/cliente_checkin', to: 'cliente#cliente_checkin'
  match '/cliente_co2ahorrado', to: 'cliente#cliente_co2ahorrado'
  match '/cliente_co2_viaje', to: 'cliente#cliente_co2_viaje'
  match '/cliente_leaderboard', to: 'cliente#cliente_leaderboard'
  match '/cliente_muestra_retro', to: 'cliente#cliente_muestra_retro'
  match '/cliente_envia_retro', to: 'cliente#cliente_envia_retro'
  match '/cliente_envia_reporte', to: 'cliente#cliente_envia_reporte'
  match '/cliente_envia_sugerencia', to: 'cliente#cliente_envia_sugerencia'
  match '/cliente_reserva_viajes', to: 'cliente#cliente_reserva_viajes'
  match '/viaje_reservaciones', to: 'cliente#viaje_reservaciones'
  match '/viaje_cierre', to: 'cliente#viaje_cierre'
  match '/viaje_apertura', to: 'cliente#viaje_apertura'

  devise_scope :user do
    match '/signup' => 'registrations#create', :via => :post
    match '/signin' => 'sessions#create', :via => :post
    match '/signinfacebook' => 'sessions#createface', :via => :post
    match '/signout' => 'sessions#destroy', :via => :delete
  end
  
end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :conductors

  resources :descuentos

  resources :reportes
  resources :users

  resources :retroaspectos

  resources :retroalimentacions

  resources :reservacions

  resources :niveles
  resources :tipomedallas
  resources :medallas
  
  resources :clientes do
    member do
      get :profile, :muro
    end
  end

  resources :administradors

  resources :rutas
  resources :paradas

  resources :vans

  resources :viajes do
    member do
      get :detalle
    end
  end

  resources :reservacions do
    member do
      get :retroalimentacion
    end
  end

  resources :retroalimentacion, only: [:create, :destroy]

  resources :reservacions, only: [:checkin]

  match '/listareportes', to: 'administradors#listareportes'
  match '/retroalimentaciones', to: 'administradors#reporteretros'
  
  match '/inicio', to: 'administradors#inicio'
  match '/entrega', to: 'administradors#entrega_regalos'
  match '/dashboard', to: 'clientes#dashboard'
  match '/promociones', to: 'clientes#promociones'
  match '/buscar', to: 'clientes#buscarviaje'
  match '/reservaciones', to: 'clientes#reservaciones'
  match '/mis_viajes', to: 'clientes#viajes'
  match '/reporte', to: 'clientes#reporte'
  match '/retro', to: 'reservacions#create_retro'
  match '/retro', to: 'reservacions#retro'
  match '/checkin', to: 'reservacions#checkin'
  match '/compartir_facebook', to: 'clientes#compartir_facebook'

  match '/formapago', to: 'clientes#formapago'
  match '/compracredito', to: 'clientes#compracredito'
  match '/create_transaction_charge', to: 'clientes#create_transaction_charge'

  match '/recarga', to: 'pagos#recarga'
  match '/compra', to: 'pagos#compra'
  match '/entrega_regalos', to: 'administradors#admin_entrega_regalo'

  match '/signup', to: 'users#new'
  match '/signout', to: 'sessions#destroy'

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match '/listadministradores', to: 'administradors#listadministradores'
  match '/administradors', to: 'administradors#index'

  match '/administrar_administradores', to: 'administradors#administradores', via:[:get, :post, :put]
  match '/administrar_administrador_detalle', to: 'administradors#administrador_detalleadministrador', via:[:get, :post, :put]
  match '/administrador_controller/jtable_list',   to: 'administradors#jtable_list',   via: [:get, :post]
  match '/administrador_controller/jtable_filterlist',   to: 'administradors#jtable_filterlist',   via: [:get, :post]
  match '/administrador_controller/jtable_create',   to: 'administradors#jtable_create',   via: [:get, :post]
  match '/administrador_controller/jtable_delete',   to: 'administradors#jtable_delete',   via: [:post]
  match '/administrador_controller/jtable_update',   to: 'administradors#jtable_update',   via: [:post]

  match '/administrador_controller/update',   to: 'administradors#update',   via: [:post,:put]
  match '/administrador_controller/create',   to: 'administradors#create',   via: [:post,:put]

  match '/administrar_conductores', to: 'administradors#conductores', via:[:get, :post, :put]
  match '/conductor_controller/jtable_list',   to: 'conductors#jtable_list',   via: [:post, :get]
  match '/conductor_controller/jtable_filterlist',   to: 'conductors#jtable_filterlist',   via: [:get, :post]
  match '/conductor_controller/jtable_create',   to: 'conductors#jtable_create',   via: [:get, :post]
  match '/conductor_controller/jtable_delete',   to: 'conductors#jtable_delete',   via: [:post]
  match '/conductor_controller/jtable_update',   to: 'conductors#jtable_update',   via: [:post]
  match '/conductor_controller/update',   to: 'conductors#update',   via: [:post,:put]
  match '/conductor_controller/create',   to: 'conductors#create',   via: [:post,:put]

  match '/administrar_promocion_saldo', to: 'administradors#promocion_saldo'
  match '/administrar_saldopromocion', to: 'administradors#saldopromocion', via:[:get, :post, :put]
  match '/administrar_saldopromocion_detalle', to: 'administradors#administrador_detallesaldopromocion', via:[:get, :post, :put]
  match '/saldopromocion_controller/jtable_filterlist',   to: 'saldopromocions#jtable_filterlist',   via: [:get, :post]
  match '/saldopromocion_controller/jtable_delete',   to: 'saldopromocions#jtable_delete',   via: [:post]
  match '/saldopromocion_controller/update',   to: 'saldopromocions#update',   via: [:post,:put]
  match '/saldopromocion_controller/create',   to: 'saldopromocions#create',   via: [:post,:put]

  match '/administrar_promocion_regalo', to: 'administradors#promocion_regalo'
  match '/administrar_regalopromocion', to: 'administradors#saldopromocion', via:[:get, :post, :put]
  match '/administrar_regalopromocion_detalle', to: 'administradors#administrador_detalleregalopromocion', via:[:get, :post, :put]
  match '/regalos_controller/jtable_filterlist',   to: 'regalos#jtable_filterlist',   via: [:get, :post]
  match '/regalos_controller/jtable_delete',   to: 'regalos#jtable_delete',   via: [:post]
  match '/regalos_controller/update',   to: 'regalos#update',   via: [:post,:put]
  match '/regalos_controller/create',   to: 'regalos#create',   via: [:post,:put]

  match '/van_controller/jtable_list',   to: 'vans#jtable_list',   via: [:get, :post]
  match '/van_controller/jtable_filterlist',   to: 'vans#jtable_filterlist',   via: [:get, :post]
  match '/van_controller/jtable_delete',   to: 'vans#jtable_delete',   via: [:post]
  match '/van_controller/create',   to: 'vans#create',   via: [:post,:put]
  match '/van_controller/update',   to: 'vans#update',   via: [:post,:put]
  match '/administrar_van_detalle',   to: 'administradors#administrador_detallevan',   via: [:get, :post, :put]

  match '/ruta_controller/jtable_list',   to: 'rutas#jtable_list',   via: [:get, :post, :put]
  match '/ruta_controller/jtable_filterlist',   to: 'rutas#jtable_filterlist',   via: [:get, :post]
  match '/ruta_controller/jtable_delete',   to: 'rutas#jtable_delete',   via: [:post]
  match '/rutas/:id', to: 'rutas#show', via: [ :get]
  match '/rutas/:id', to: 'rutas#actualizar', via: [:post, :put]

  match '/administrar_ruta_detalle',   to: 'rutas#administrador_detalleruta',   via: [:get, :post, :put]
  match '/administrar_clientes', to: 'administradors#clientes', via:[:get, :post, :put]
  match '/administrar_cliente_detalle', to: 'administradors#administrador_detallecliente', via:[:get, :post, :put]
  match '/cliente_controller/jtable_list',   to: 'clientes#jtable_list',   via: [:post, :get]
  match '/cliente_controller/jtable_filterlist',   to: 'clientes#jtable_filterlist',   via: [:get, :post]
  match '/cliente_controller/jtable_delete',   to: 'clientes#jtable_delete',   via: [:post]
  match '/cliente_controller/jtable_update',   to: 'clientes#jtable_update',   via: [:post]
  match '/cliente_controller/update',   to: 'clientes#update',   via: [:post,:put]
  match '/cliente_controller/create',   to: 'clientes#create',   via: [:post,:put]

  match '/sugerencias', to: 'administradors#sugerencias', via:[:get, :post, :put]
  match '/sugerencia_controller/jtable_list',   to: 'sugerencias#jtable_list',   via: [:post, :get]
  match '/sugerencia_controller/jtable_filterlist',   to: 'sugerencias#jtable_filterlist',   via: [:get, :post]
  match '/administrar_sugerencia_detalle',   to: 'administradors#administrador_detallesugerencia',   via: [:get, :post, :put]

  match '/procesar_busqueda',   to: 'clientes#procesarbusquedaviaje',   via: [:get, :post]
  match '/procesar_busqueda_sinlogin',   to: 'static_pages#procesarbusqueda_sinlogin',   via: [:get, :post]

  match '/administrar_medallas', to: 'administradors#medallas', via:[:get, :post, :put]
  match '/medalla_controller/jtable_list',   to: 'medallas#jtable_list',   via: [:post, :get]
  match '/medalla_controller/jtable_filterlist',   to: 'medallas#jtable_filterlist',   via: [:get, :post]
  match '/medalla_controller/jtable_create',   to: 'medallas#jtable_create',   via: [:get, :post]
  match '/medalla_controller/jtable_delete',   to: 'medallas#jtable_delete',   via: [:post]
  match '/medalla_controller/jtable_update',   to: 'medallas#jtable_update',   via: [:post]
  match '/medalla_controller/update',   to: 'medallas#update',   via: [:post,:put]
  match '/medalla_controller/create',   to: 'medallas#create',   via: [:post,:put]

app/models/reservacion.rb
class Reservacion < ActiveRecord::Base
  attr_accessible :cliente_id, :estadotipo_id, :estatus, :referenciapago_id, :viaje_id
  belongs_to :cliente
  belongs_to :viaje
  has_many :retroalimentacions
  has_one :share

end

app/controllers/reservacions_controller.rb
class ReservacionsController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy, :retro]
  # GET /reservacions
  # GET /reservacions.json
  def index
    @reservacions = Reservacion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservacions }
    end
  end

  # GET /reservacions/1
  # GET /reservacions/1.json
  def show
    @reservacion = Reservacion.find(params[:id])
    @current_cliente = obtener_cliente(current_user)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reservacion }
    end
  end

  # GET /reservacions/new
  # GET /reservacions/new.json
  def new
    @reservacion = Reservacion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reservacion }
    end
  end

  # GET /reservacions/1/edit
  def edit
    @reservacion = Reservacion.find(params[:id])
  end

  # POST /reservacions
  # POST /reservacions.json
  def create
    @reservacion = Reservacion.new(params[:reservacion])

    respond_to do |format|
      if @reservacion.save
        format.html { redirect_to @reservacion, notice: 'Reservacion was successfully created.' }
        format.json { render json: @reservacion, status: :created, location: @reservacion }
      else
        format.html { render action: "new" }
        format.json { render json: @reservacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservacions/1
  # PUT /reservacions/1.json
  def update
    @reservacion = Reservacion.find(params[:id])

    respond_to do |format|
      if @reservacion.update_attributes(params[:reservacion])
        format.html { redirect_to @reservacion, notice: 'Reservacion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reservacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservacions/1
  # DELETE /reservacions/1.json
  def destroy
    @reservacion = Reservacion.find(params[:id])
    @reservacion.destroy

    respond_to do |format|
      format.html { redirect_to reservacions_url }
      format.json { head :no_content }
    end
  end

  def retroalimentacion
    @title="Evalua el servicio"
    @current_cliente = obtener_cliente(current_user)
    @aspectos=aspectos
    @reservacion=params[:id]
    @reserva=Reservacion.find(@reservacion)
    render 'show_retro'
  end

  def create_retro
    id=params[:reservacion_id]
    reservacion=Reservacion.find(id)
    @current_cliente = obtener_cliente(reservacion.cliente.user)
    aspectos.each do |aspecto|
      calificacion=params[:"#{aspecto.id}"]
      retro = Retroalimentacion.create(reservacion_id:id,aspecto_id:aspecto.id,tipocalificacion_id:calificacion)
    end
    asigna_medalla_retro(@current_cliente)
    aumenta_puntos(@current_cliente,50)
    redirect_to :controller => 'clientes', :action => 'dashboard'
  end

end

app/helpers/reservacions_helper.rb
module ReservacionsHelper

	def reservacion_realizada(reservacion)
		reservacion.estadotipo_id=3
		reservacion.save
	end

	def existe_retroalimentacion(reservacion)
		if(Retroalimentacion.find_all_by_reservacion_id(reservacion.id).count>0)
			return true
		else
			return false
		end
	end

end

app/views/reservacions/_form.html.erb
<%= form_for(@reservacion) do |f| %>
  <% if @reservacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservacion.errors.count, "error") %> prohibited this reservacion from being saved:</h2>

      <ul>
      <% @reservacion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :viaje_id %><br />
    <%= f.number_field :viaje_id %>
  </div>
  <div class="field">
    <%= f.label :cliente_id %><br />
    <%= f.number_field :cliente_id %>
  </div>
  <div class="field">
    <%= f.label :referenciapago_id %><br />
    <%= f.number_field :referenciapago_id %>
  </div>
  <div class="field">
    <%= f.label :estadotipo_id %><br />
    <%= f.number_field :estadotipo_id %>
  </div>
  <div class="field">
    <%= f.label :estatus %><br />
    <%= f.check_box :estatus %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservacions/edit.html.erb
<h1>Editing reservacion</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservacion %> |
<%= link_to 'Back', reservacions_path %>

app/views/reservacions/index.html.erb
<h1>Listing reservacions</h1>

<table>
  <tr>
    <th>Viaje</th>
    <th>Cliente</th>
    <th>Referenciapago</th>
    <th>Estadostipo</th>
    <th>Estatus</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reservacions.each do |reservacion| %>
  <tr>
    <td><%= reservacion.viaje_id %></td>
    <td><%= reservacion.cliente_id %></td>
    <td><%= reservacion.referenciapago_id %></td>
    <td><%= reservacion.estadostipo %></td>
    <td><%= reservacion.estatus %></td>
    <td><%= link_to 'Show', reservacion %></td>
    <td><%= link_to 'Edit', edit_reservacion_path(reservacion) %></td>
    <td><%= link_to 'Destroy', reservacion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reservacion', new_reservacion_path %>

app/views/reservacions/new.html.erb
<h1>New reservacion</h1>

<%= render 'form' %>

<%= link_to 'Back', reservacions_path %>

app/views/reservacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Viaje:</b>
  <%= @reservacion.viaje_id %>
</p>

<p>
  <b>Cliente:</b>
  <%= @reservacion.cliente_id %>
</p>

<p>
  <b>Referenciapago:</b>
  <%= @reservacion.referenciapago_id %>
</p>

<p>
  <b>Estadostipo:</b>
  <%= @reservacion.estadotipo_id %>
</p>

<p>
  <b>Estatus:</b>
  <%= @reservacion.estatus %>
</p>


<%= link_to 'Edit', edit_reservacion_path(@reservacion) %> |
<%= link_to 'Back', reservacions_path %>

app/views/reservacions/show_retro.html.erb
 <% provide(:title, @title) %>
 <div class="wrapper row-offcanvas row-offcanvas-left">
    <aside class="left-side sidebar-offcanvas">
        <%= render 'shared/user_sidebar' %> 
    </aside>
    <aside class="right-side">
    <section class="content-header">
        <h1>Evaluación del servicio<small>Detalle</small></h1>
        <ol class="breadcrumb">
            <li><a href="/dashboard"><i class="fa fa-home"></i> Inicio</a></li>
            <li class="active">Feedback</li>
        </ol>
    </section>
    <section class="content">
        <div class="row-fluid">
            <div class="form-group well well-large">
                        <div class="row-fluid">
                            <div class="span4">
                                 <h4>
                        Ruta &nbsp<%=@reserva.viaje.ruta.nombre%> 
                        </h4>
                        <h5>
                        Fecha: <b>&nbsp<%=@reserva.viaje.fecha.strftime("%d/%m/%Y")%></b>
                        </h5>
                            </div>
                            <div class="span4">
                                <h5>
                        Hora Salida: <b>&nbsp<%=@reserva.viaje.horainicio.strftime("%I:%M%p")%></b>
                        </h5>
                        <h5>
                        Hora llegada: <b>&nbsp<%=(@reserva.viaje.horainicio+ @reserva.viaje.ruta.paradas.sum(:tiempo).to_i).strftime("%I:%M%p")%></b>
                        </h5>
                        
                            </div>

                            <div class="span4">
                                <h5>
                        Conductor: <b>&nbsp<%=@reserva.viaje.ruta.nombre%> </b>
                        </h5>
                        
                            </div>
                        </div>
   
                </div>
            <div class="row-fluid">
                <div class="span12">
                    <%= render 'shared/user_feedback' %>
                </div>
            </div>
        </div>
    </section>                                  
    </aside><!-- /.right-side -->
</div><!-- ./wrapper -->